export { default as Home } from './Home/Home'
export { default as Following } from './Following/Following'
export { default as Profile } from './Profile/Profile'
export { default as Live } from './Live/Live'
export { default as Upload } from './Upload/Upload'